# Numpy
- Numpy is a linear algebra lib in python.
- almost all of the libraries in the PyData ecosystem rely on Numpy
- has many built-in functions
- some of the most important aspects of Numpy are
    - Arrays
    - Vectors - Strictly 1-D arrays
    - Matrices - 2-D arrays(a matrix can still have one row and one column)
    - Number generations
- Reasons to use Numpy instead of standard List object are
    - Memory effiiency
    - Easily expands to N-dimensional objects
    - Broadcasting operations and functions with numpy
    - All Data Science and ML lib are built with Numpy
 

## Creating Numpy Arrays from List
- np.array()

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
my_array = np.array(my_list)

In [5]:
my_array

array([1, 2, 3])

In [6]:
type(my_list)

list

In [7]:
type(my_array)

numpy.ndarray

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
my_array = np.array(my_matrix)
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Built-in Methods to create arrays
- arange()
- Zeros()
- Ones()
- linpsace()
- eye()
- rand() - Creates random sample from a uniform distribution
- randn() - Creates random sample from a standard normal distribution
- randint() - Returns random integers from low to high(exclusive)
- seed()

In [11]:
np.arange(2,5)

array([2, 3, 4])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.linspace(0,11,3)

array([ 0. ,  5.5, 11. ])

In [24]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [25]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.eye(1)

array([[1.]])

In [6]:
np.random.rand(2)

array([0.8187469, 0.0270756])

In [30]:
np.random.rand(5,5)

array([[0.21994552, 0.62854272, 0.35243083, 0.86936552, 0.58865937],
       [0.06808759, 0.76605555, 0.73664753, 0.6159479 , 0.63496017],
       [0.04737699, 0.49609365, 0.79831487, 0.80286826, 0.30224811],
       [0.92169869, 0.94188449, 0.52705048, 0.56596141, 0.39972836],
       [0.7466253 , 0.98275779, 0.76064947, 0.96193801, 0.68461182]])

In [31]:
np.random.rand(3,2)

array([[0.60152352, 0.33590575],
       [0.68906954, 0.36365803],
       [0.13507146, 0.93045011]])

In [8]:
np.random.randn(2)

array([0.5595774 , 0.55663288])

In [8]:
np.random.randn(5,5)

array([[ 0.62704871,  0.2392365 ,  0.49450991,  0.16585358,  0.1107268 ],
       [-0.35756365, -1.27149389, -0.29285121, -1.42669913,  0.14035048],
       [ 0.23082167,  1.20374655, -0.22151758, -0.29983758, -0.10193473],
       [-0.50448831,  0.58585043, -0.03842285,  0.59959191,  0.86467369],
       [ 2.46167675,  1.27348195, -0.87144164,  1.19959706, -0.46728892]])

In [7]:
np.random.randint(1,100,(10,10))

array([[73, 75,  9, 16, 24, 89, 74, 39,  2, 81],
       [15, 26, 53, 88, 86, 11, 54, 95, 59, 53],
       [78, 89, 97, 82, 52, 77,  3, 70, 42, 12],
       [59, 97, 70, 68, 69, 98, 51, 95, 91, 32],
       [13,  8, 37, 96, 91, 99, 40, 37, 96, 77],
       [81, 85, 42, 16, 33, 84, 23, 21, 67, 29],
       [33, 26, 32, 59, 74, 33, 21, 52, 34, 77],
       [17, 81, 44, 21, 44, 17,  5, 52, 92, 45],
       [49, 17, 53, 75, 37,  5, 62, 11, 19,  5],
       [34, 76, 79, 74, 37, 32, 43, 74, 18, 52]])

In [36]:
np.random.randint(1,100,5)

array([55, 14, 66,  5, 79])

In [37]:
np.random.seed(15)
np.random.randint(1,19,5)

array([ 9, 13,  6,  1,  8])

In [39]:
np.random.seed(15)
np.random.randint(2,19,5)

array([10, 14,  7,  2,  9])

In [40]:
np.random.seed(15)
np.random.randint(2,19,5)

array([10, 14,  7,  2,  9])

## Array Attributes and Methods
 - reshape()
 - max()
 - min()
 - argmax()
 - argmin()
 - shape()

In [27]:
arr_check = np.random.randint(0,10,(3,3))
print(arr_check)

[[7 2 8]
 [3 9 1]
 [6 5 7]]


In [29]:
ranarr = np.random.randint(0,50,(5,2))
print(ranarr)

[[45 42]
 [ 8 40]
 [ 7 11]
 [35 12]
 [38 30]]


In [64]:
shaped_ranarr = ranarr.reshape(5,2)

In [65]:
shaped_ranarr

array([[11, 21],
       [47, 29],
       [17, 45],
       [31, 23],
       [32, 10]])

In [45]:
arr = np.arange(0,25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.min()

0

In [53]:
arr.argmin()

0

In [54]:
arr.max()

24

In [56]:
arr.argmax()

24

In [59]:
arr.shape

(25,)

In [60]:
ranarr.shape


(10,)

In [63]:
shaped_ranarr.shape

(5, 2)

## Numpy Indexing and Selection


In [66]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[8]

8

In [69]:
arr[1:5]

array([1, 2, 3, 4])

In [70]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting
- The difference between Python List and Numpy arrays is the ability to broadcast

In [71]:
arr[0:5] = 100

In [72]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [73]:
arr = np.arange(0,11)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
slice_of_arr = arr[0:6]

In [76]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [77]:
slice_of_arr[0:4] = 50

In [78]:
slice_of_arr

array([50, 50, 50, 50,  4,  5])

In [79]:
arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr_copy = arr.copy()

In [81]:
arr_copy

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr_copy[:] = 100

In [83]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [84]:
arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

## Indexing a 2D array

In [87]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [88]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [89]:
arr_2d[1]

array([20, 25, 30])

In [90]:
arr_2d[1][1]

25

In [91]:
arr_2d[1][0]

20

In [93]:
arr_2d[1,0]

20

In [94]:
arr_2d[1,1]

25

In [95]:
arr_2d[1:3,1:]

array([[25, 30],
       [40, 45]])

In [96]:
arr_2d[2,:]

array([35, 40, 45])

## Conditional Selection

In [97]:
arr = np.arange(1,11)

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [100]:
bool_arr = arr > 4

In [101]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [102]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [103]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

## Numpy Operations

In [106]:
arr = np.arange(0,10)

In [107]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [109]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [110]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [111]:
arr / arr

<ipython-input-111-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [112]:
1 / arr

<ipython-input-112-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [113]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

In [114]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [115]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [116]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [117]:
np.log(arr)

<ipython-input-117-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Summary Statistics on Arrays

In [118]:
arr = np.arange(0,10)

In [119]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
arr.sum()

45

In [121]:
arr.max()

9

In [122]:
arr.mean()

4.5

In [123]:

arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [124]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [125]:
arr_2d.sum(axis = 0)

array([15, 18, 21, 24])

In [126]:
arr_2d.sum(axis = 1)

array([10, 26, 42])

In [128]:
arr_2d.shape


(3, 4)